# Generated by Django 5.0.6 on 2024-07-07 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=255)),
                ('numero_repeticiones', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('musculo_ejercitar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DatosFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('imc', models.FloatField()),
                ('masa_muscular', models.FloatField()),
                ('recomendaciones', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuarios', models.ManyToManyField(related_name='coaches', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos_app.rutina')),
            ],
        ),
    ]
