# Generated by Django 5.0.6 on 2024-06-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_app', '0002_usuariodatosmembresia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=255)),
                ('numero_repeticiones', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('musculo_ejercitar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('usuarios', models.ManyToManyField(related_name='coaches', to='usuarios_app.usuario')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos_app.rutina')),
            ],
        ),
    ]
