# Generated by Django 5.0.6 on 2024-06-26 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos_app', '0001_initial'),
        ('usuarios_app', '0002_usuariodatosmembresia_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosFisicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('imc', models.FloatField()),
                ('masa_muscular', models.FloatField()),
                ('recomendaciones', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios_app.usuario')),
            ],
        ),
    ]
