# Generated by Django 5.0.6 on 2024-06-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos_app', '0002_datosfisicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='rutina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos_app.rutina'),
        ),
    ]
