# Generated by Django 5.0.6 on 2024-06-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='userDefect.jpg', null=True, upload_to='users/'),
        ),
    ]
