# Generated by Django 5.0.6 on 2024-06-23 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodatosmembresia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
